avList1 = {
	"avgaurd.exe": "avira antivir",
	"cpf.exe": "comodo",
	"emet_agent.exe": "emet",
	"emet_service.exe": "emet",
	"avconsol.exe": "mcafee",
	"avsynmgr.exe": "mcafee",
	"cpd.exe": "mcafee",
	"firesvc.exe": "mcafee",
	"firetray.exe": "mcafee",
	"hipsvc.exe": "mcafee",
	"mcafeefire.exe": "mcafee",
	"mcscript.exe": "mcafee",
	"updaterui.exe": "mcafee",
	"cleanup.exe": "mcafee",
	"cmdagent.exe": "mcafee",
	"frminst.exe": "mcafee",
	"mcscript_inuse.exe": "mcafee",
	"alogserv.exe": "mcafee virusscan",
	"_avp32.exe": "卡巴斯基",
	"_avpcc.exe": "卡巴斯基",
	"_avpm.exe": "卡巴斯基",
	"alertsvc.exe": "norton antivirus",
	"anti-trojan.exe": "anti-trojan elite",
	"arr.exe": "application request route",
	"atguard.exe": "antivir",
	"atwatch.exe": "mustek",
	"au.exe": "nsis",
	"aupdate.exe": "symantec",
	"autodown.exe": "antivirus autoupdater",
	"aavgapi.exe": "avg",
	"avgcc32.exe": "avg",
	"avgctrl.exe": "avg",
	"avgemc.exe": "avg",
	"avgrsx.exe": "avg",
	"avgserv.exe": "avg",
	"avgserv9.exe": "avg",
	"avgw.exe": "avg",
	"avkpop.exe": "g data software ag",
	"avkserv.exe": "g data software ag",
	"avkservice.exe": "g data software ag",
	"avkwctl9.exe": "g data software ag",
	"avltmain.exe": "panda software aplication",
	"avnt.exe": "h+bedv datentechnik gmbh",
	"avpdos32.exe": "kaspersky antivirus",
	"avpm.exe": "kaspersky antivirus",
	"avptc32.exe": "kaspersky antivirus",
	"avpupd.exe": "kaspersky antivirus",
	"avwin.exe": "h+bedv",
	"bargains.exe": "exact advertising spyware",
	"beagle.exe": "avast",
	"blackd.exe": "blackice",
	"blackice.exe": "blackice",
	"blink.exe": "micromedia",
	"blss.exe": "cblaster",
	"bootwarn.exe": "symantec",
	"bpc.exe": "grokster",
	"brasil.exe": "exact advertising",
	"ccevtmgr.exe": "norton internet security",
	"cdp.exe": "cyberlink corp.",
	"cfd.exe": "motive communications",
	"cfgwiz.exe": "norton antivirus",
	"clean.exe": "windows流氓软件清理大师",
	"cleaner.exe": "windows流氓软件清理大师",
	"cleaner3.exe": "windows流氓软件清理大师",
	"cleanpc.exe": "windows流氓软件清理大师",
	"defalert.exe": "symantec",
	"defscangui.exe": "symantec",
	"defwatch.exe": "norton antivirus",
	"dpps2.exe": "panicware",
	"dssagent.exe": "broderbund",
	"emsw.exe": "alset inc",
	"ethereal.exe": "rationalclearcase",
	"fast.exe": "fastusr",
	"fch32.exe": "f-secure",
	"fih32.exe": "f-secure",
	"findviru.exe": "f-secure",
	"firewall.exe": "ashampoosoftware",
	"fnrb32.exe": "f-secure",
	"fp-win.exe": "f-prot antivirus ondemand",
	"fsaa.exe": "f-secure",
	"fsav.exe": "f-secure",
	"fsav32.exe": "f-secure",
	"fsav530stbyb.exe": "f-secure",
	"fsav530wtbyb.exe": "f-secure",
	"fsav95.exe": "f-secure",
	"fsgk32.exe": "f-secure",
	"fsm32.exe": "f-secure",
	"fsma32.exe": "f-secure",
	"fsmb32.exe": "f-secure",
	"guard.exe": "ewido",
	"guarddog.exe": "ewido",
	"htpatch.exe": "silicon integrated systems corporation",
	"iamapp.exe": "symantec",
	"iamserv.exe": "symantec",
	"iamstats.exe": "symantec",
	"iedriver.exe": "urlblaze.com",
	"iface.exe": "panda antivirus module",
	"infus.exe": "infus dialer",
	"infwin.exe": "msviewparasite",
	"intdel.exe": "inet delivery",
	"keenvalue.exe": "euniverse inc",
	"launcher.exe": "intercort systems",
	"ldscan.exe": "windows trojans inspector",
	"luall.exe": "symantec",
	"luau.exe": "symantec",
	"lucomserver.exe": "norton",
	"mcagent.exe": "mcafee",
	"mcmnhdlr.exe": "mcafee",
	"mctool.exe": "mcafee",
	"mcupdate.exe": "mcafee",
	"mcvsrte.exe": "mcafee",
	"mcvsshld.exe": "mcafee",
	"mfin32.exe": "myfreeinternetupdate",
	"mfw2en.exe": "myfreeinternetupdate",
	"mfweng3.02d30.exe": "myfreeinternetupdate",
	"mgavrtcl.exe": "mcafee",
	"mgavrte.exe": "mcafee",
	"mghtml.exe": "mcafee",
	"mgui.exe": "bullguard",
	"mmod.exe": "ezulainc",
	"mostat.exe": "wurldmediainc",
	"mpfagent.exe": "mcafee",
	"mpfservice.exe": "mcafee",
	"mpftray.exe": "mcafee",
	"mscache.exe": "integrated search technologies spyware",
	"mscman.exe": "odysseusmarketinginc",
	"msmgt.exe": "total velocity spyware",
	"msvxd.exe": "w32/datom-a",
	"nav.exe": "reuters limited",
	"navapsvc.exe": "norton antivirus",
	"navapw32.exe": "norton antivirus",
	"navw32.exe": "norton antivirus",
	"ndd32.exe": "诺顿磁盘医生",
	"nisserv.exe": "norton",
	"nisum.exe": "norton",
	"nmain.exe": "norton",
	"nprotect.exe": "symantec",
	"npscheck.exe": "norton",
	"npssvc.exe": "norton",
	"outpostinstall.exe": "outpost",
	"patch.exe": "趋势科技",
	"pcscan.exe": "趋势科技",
	"persfw.exe": "tiny personal firewall",
	"pgmonitr.exe": "promulgate spyware",
	"pop3trap.exe": "pc-cillin",
	"poproxy.exe": "nortonantivirus",
	"powerscan.exe": "integrated search technologies",
	"prizesurfer.exe": "prizesurfer",
	"prmt.exe": "opistat",
	"prmvr.exe": "adtomi",
	"processmonitor.exe": "sysinternals",
	"protectx.exe": "protectx",
	"qconsole.exe": "norton antivirus quarantine console",
	"qserver.exe": "norton internet security",
	"rapapp.exe": "blackice",
	"rb32.exe": "rapidblaster",
	"rcsync.exe": "prizesurfer",
	"realmon.exe": "realmon",
	"rescue32.exe": "卡巴斯基互联网安全套装",
	"rtvscn95.exe": "real-time virus scanner",
	"rulaunch.exe": "mcafee user interface",
	"run32dll.exe": "pal pc spy",
	"safeweb.exe": "psafe tecnologia",
	"sbserv.exe": "norton antivirus",
	"sfc.exe": "system file checker",
	"sh.exe": "mks toolkit for win3",
	"showbehind.exe": "microsmarts enterprise component",
	"soap.exe": "system soap pro",
	"supporter5.exe": "escorcher反病毒",
	"symproxysvc.exe": "symantec",
	"symtray.exe": "symantec",
	"tbscan.exe": "thunderbyte",
	"tc.exe": "timecalende",
	"titanin.exe": "titanhide",
	"tvmd.exe": "total velocity",
	"tvtmd.exe": "total velocity",
	"vettray.exe": "etrust",
	"vpc32.exe": "symantec",
	"vpc42.exe": "symantec",
	"vshwin32.exe": "mcafee",
	"vsmain.exe": "mcafee",
	"vsstat.exe": "mcafee",
	"zapro.exe": "zone alarm",
	"zonealarm.exe": "zone alarm",
	"a2cmd.exe": "emsisoft anti-malware",
	"a2service.exe": "a-squared free",
	"a2free.exe": "a-squared free",
	"advchk.exe": "norton antivirus",
	"agb.exe": "安天防线",
	"ahprocmonserver.exe": "安天防线",
	"airdefense.exe": "airdefense",
	"avira.exe": "小红伞杀毒",
	"amon.exe": "tiny personal firewall",
	"avz.exe": "avz",
	"apvxdwin.exe": "熊猫卫士",
	"ashmaisv.exe": "alwil",
	"ashserv.exe": "avast anti-virus",
	"ashsimpl.exe": "avast!viruscleaner",
	"ashwebsv.exe": "avast",
	"aswupdsv.exe": "avast",
	"aswscan.exe": "avast",
	"avciman.exe": "熊猫卫士",
	"avengine.exe": "熊猫卫士",
	"avesvc.exe": "avira antivir security service",
	"avgchsvx.exe": "avg",
	"avgcsrvx.exe": "avg",
	"avgnsx.exe": "avg",
	"avgfwsrv.exe": "avg",
	"avgntmgr.exe": "avg",
	"avgtray.exe": "avg",
	"avgupsvc.exe": "avg",
	"avinitnt.exe": "command antivirus for nt server",
	"avserver.exe": "kerio mailserver",
	"avsched32.exe": "h+bedv",
	"avwupsrv.exe": "h+bedv",
	"bdswitch.exe": "bitdefender module",
	"clamwin.exe": "clamwin portable",
	"cureit.exe": "drweb cureit",
	"drwadins.exe": "dr.web",
	"drweb.exe": "dr.web",
	"defenderdaemon.exe": "shadowdefender",
	"ewidoctrl.exe": "ewido security suite",
	"ezantivirusregistrationcheck.exe": "e-trust antivirus",
	"fprottray.exe": "f-prot antivirus",
	"fpwin.exe": "verizon",
	"freshclam.exe": "clamav",
	"fsbwsys.exe": "f-secure",
	"fsdfwd.exe": "f-secure",
	"fsgk32st.exe": "f-secure",
	"fssm32.exe": "f-secure",
	"guardgui.exe": "网游保镖",
	"guardnt.exe": "ikarus",
	"inocit.exe": "etrust",
	"inorpc.exe": "etrust",
	"inort.exe": "etrust",
	"inotask.exe": "etrust",
	"inouptng.exe": "etrust",
	"isafe.exe": "etrust",
	"kav.exe": "kaspersky",
	"kavmm.exe": "kaspersky",
	"kavpf.exe": "kaspersky",
	"kazza.exe": "kaspersky",
	"kavpfw.exe": "kaspersky",
	"kavstart.exe": "kaspersky",
	"kavsvc.exe": "kaspersky",
	"kavsvcui.exe": "kaspersky",
	"kmailmon.exe": "金山毒霸",
	"mcregwiz.exe": "mcafee",
	"minilog.exe": "zone alarm",
	"myagtsvc.exe": "mcafee",
	"myagttry.exe": "mcafee",
	"navlu32.exe": "norton",
	"neowatchlog.exe": "neowatch",
	"neowatchtray.exe": "neowatch",
	"nod32.exe": "eset nod32",
	"npfmsg.exe": "norman个人防火墙",
	"nsmdtr.exe": "norton",
	"ofcpfwsvc.exe": "officescannt",
	"op_mon.exe": "outpostfirewall",
	"pavfires.exe": "熊猫卫士",
	"pavfnsvr.exe": "熊猫卫士",
	"pavkre.exe": "熊猫卫士",
	"pavprot.exe": "熊猫卫士",
	"pavproxy.exe": "熊猫卫士",
	"pavprsrv.exe": "熊猫卫士",
	"pavsrv51.exe": "熊猫卫士",
	"pavss.exe": "熊猫卫士",
	"pccguide.exe": "pc-cillin",
	"pcciomon.exe": "pc-cillin",
	"pccntmon.exe": "pc-cillin",
	"pccpfw.exe": "趋势科技",
	"pcctlcom.exe": "趋势科技",
	"pctav.exe": "pc tools antivirus",
	"pestpatrol.exe": "ikarus",
	"prevsrv.exe": "熊猫卫士",
	"savadminservice.exe": "sav",
	"savmain.exe": "sav",
	"savscan.exe": "sav",
	"sdhelp.exe": "spyware doctor",
	"spidercpl.exe": "dr.web",
	"spiderml.exe": "dr.web",
	"spiderui.exe": "dr.web",
	"spybotsd.exe": "spybot",
	"swagent.exe": "sonicwall",
	"swdoctor.exe": "sonicwall",
	"swnetsup.exe": "sophos",
	"symsport.exe": "sysmantec",
	"symwsc.exe": "sysmantec",
	"synmgr.exe": "sysmantec",
	"tmlisten.exe": "趋势科技",
	"tmntsrv.exe": "趋势科技",
	"tmproxy.exe": "趋势科技",
	"tnbutil.exe": "anti-virus",
	"vcrmon.exe": "viruschaser",
	"vrmonnt.exe": "hauri",
	"vrmonsvc.exe": "hauri",
	"xcommsvr.exe": "bitdefender",
	"afwserv.exe": "avast antivirus",
	"ksafesvc.exe": "金山毒霸",
	"kwatch.exe": "金山毒霸",
	"scan32.exe": "已知杀软进程,名称暂未收录",
	"aawtray.exe": "已知杀软进程,名称暂未收录",
	"ad-aware.exe": "已知杀软进程,名称暂未收录",
	"ackwin32.exe": "已知杀软进程,名称暂未收录",
	"adaware.exe": "已知杀软进程,名称暂未收录",
	"advxdwin.exe": "已知杀软进程,名称暂未收录",
	"agentsvr.exe": "已知杀软进程,名称暂未收录",
	"agentw.exe": "已知杀软进程,名称暂未收录",
	"alevir.exe": "已知杀软进程,名称暂未收录",
	"amon9x.exe": "已知杀软进程,名称暂未收录",
	"antivirus.exe": "已知杀软进程,名称暂未收录",
	"ants.exe": "已知杀软进程,名称暂未收录",
	"apimonitor.exe": "已知杀软进程,名称暂未收录",
	"aplica32.exe": "已知杀软进程,名称暂未收录",
	"atcon.exe": "已知杀软进程,名称暂未收录",
	"atro55en.exe": "已知杀软进程,名称暂未收录",
	"atupdater.exe": "已知杀软进程,名称暂未收录",
	"auto-protect.nav80try.exe": "已知杀软进程,名称暂未收录",
	"autotrace.exe": "已知杀软进程,名称暂未收录",
	"autoupdate.exe": "已知杀软进程,名称暂未收录",
	"ave32.exe": "已知杀软进程,名称暂未收录",
	"avp32.exe": "已知杀软进程,名称暂未收录",
	"avpcc.exe": "已知杀软进程,名称暂未收录",
	"avwin95.exe": "已知杀软进程,名称暂未收录",
	"avwinnt.exe": "已知杀软进程,名称暂未收录",
	"avwupd.exe": "已知杀软进程,名称暂未收录",
	"avwupd32.exe": "已知杀软进程,名称暂未收录",
	"avxmonitor9x.exe": "已知杀软进程,名称暂未收录",
	"avxmonitornt.exe": "已知杀软进程,名称暂未收录",
	"avxquar.exe": "已知杀软进程,名称暂未收录",
	"backweb.exe": "已知杀软进程,名称暂未收录",
	"bd_professional.exe": "已知杀软进程,名称暂未收录",
	"belt.exe": "已知杀软进程,名称暂未收录",
	"bidef.exe": "已知杀软进程,名称暂未收录",
	"bidserver.exe": "已知杀软进程,名称暂未收录",
	"bipcp.exe": "已知杀软进程,名称暂未收录",
	"bipcpevalsetup.exe": "已知杀软进程,名称暂未收录",
	"bisp.exe": "已知杀软进程,名称暂未收录",
	"bootconf.exe": "已知杀软进程,名称暂未收录",
	"borg2.exe": "已知杀软进程,名称暂未收录",
	"bs120.exe": "已知杀软进程,名称暂未收录",
	"bundle.exe": "已知杀软进程,名称暂未收录",
	"bvt.exe": "已知杀软进程,名称暂未收录",
	"ccpxysvc.exe": "已知杀软进程,名称暂未收录",
	"cfiadmin.exe": "已知杀软进程,名称暂未收录",
	"cfiaudit.exe": "已知杀软进程,名称暂未收录",
	"cfinet.exe": "已知杀软进程,名称暂未收录",
	"cfinet32.exe": "已知杀软进程,名称暂未收录",
	"claw95.exe": "已知杀软进程,名称暂未收录",
	"claw95cf.exe": "已知杀软进程,名称暂未收录",
	"click.exe": "已知杀软进程,名称暂未收录",
	"cmesys.exe": "已知杀软进程,名称暂未收录",
	"cmgrdian.exe": "已知杀软进程,名称暂未收录",
	"cmon016.exe": "已知杀软进程,名称暂未收录",
	"connectionmonitor.exe": "已知杀软进程,名称暂未收录",
	"cpf9x206.exe": "已知杀软进程,名称暂未收录",
	"cpfnt206.exe": "已知杀软进程,名称暂未收录",
	"ctrl.exe": "已知杀软进程,名称暂未收录",
	"cv.exe": "已知杀软进程,名称暂未收录",
	"cwnb181.exe": "已知杀软进程,名称暂未收录",
	"cwntdwmo.exe": "已知杀软进程,名称暂未收录",
	"datemanager.exe": "已知杀软进程,名称暂未收录",
	"dcomx.exe": "已知杀软进程,名称暂未收录",
	"deputy.exe": "已知杀软进程,名称暂未收录",
	"divx.exe": "已知杀软进程,名称暂未收录",
	"dllcache.exe": "已知杀软进程,名称暂未收录",
	"dllreg.exe": "已知杀软进程,名称暂未收录",
	"doors.exe": "已知杀软进程,名称暂未收录",
	"dpf.exe": "已知杀软进程,名称暂未收录",
	"dpfsetup.exe": "已知杀软进程,名称暂未收录",
	"drwatson.exe": "已知杀软进程,名称暂未收录",
	"drweb32.exe": "已知杀软进程,名称暂未收录",
	"drwebupw.exe": "已知杀软进程,名称暂未收录",
	"dvp95.exe": "已知杀软进程,名称暂未收录",
	"dvp95_0.exe": "已知杀软进程,名称暂未收录",
	"ecengine.exe": "已知杀软进程,名称暂未收录",
	"efpeadm.exe": "已知杀软进程,名称暂未收录",
	"ent.exe": "已知杀软进程,名称暂未收录",
	"esafe.exe": "已知杀软进程,名称暂未收录",
	"escanhnt.exe": "已知杀软进程,名称暂未收录",
	"escanv95.exe": "已知杀软进程,名称暂未收录",
	"espwatch.exe": "已知杀软进程,名称暂未收录",
	"etrustcipe.exe": "已知杀软进程,名称暂未收录",
	"evpn.exe": "已知杀软进程,名称暂未收录",
	"exantivirus-cnet.exe": "已知杀软进程,名称暂未收录",
	"exe.avxw.exe": "已知杀软进程,名称暂未收录",
	"expert.exe": "已知杀软进程,名称暂未收录",
	"explore.exe": "已知杀软进程,名称暂未收录",
	"f-agnt95.exe": "已知杀软进程,名称暂未收录",
	"f-prot95.exe": "已知杀软进程,名称暂未收录",
	"f-stopw.exe": "已知杀软进程,名称暂未收录",
	"fameh32.exe": "已知杀软进程,名称暂未收录",
	"fp-win_trial.exe": "已知杀软进程,名称暂未收录",
	"fprot.exe": "已知杀软进程,名称暂未收录",
	"frw.exe": "已知杀软进程,名称暂未收录",
	"fsgk32.exe": "已知杀软进程,名称暂未收录",
	"gator.exe": "已知杀软进程,名称暂未收录",
	"gbmenu.exe": "已知杀软进程,名称暂未收录",
	"gbpoll.exe": "已知杀软进程,名称暂未收录",
	"generics.exe": "已知杀软进程,名称暂未收录",
	"gmt.exe": "已知杀软进程,名称暂未收录",
	"hacktracersetup.exe": "已知杀软进程,名称暂未收录",
	"hbinst.exe": "已知杀软进程,名称暂未收录",
	"hbsrv.exe": "已知杀软进程,名称暂未收录",
	"hotactio.exe": "已知杀软进程,名称暂未收录",
	"hotpatch.exe": "已知杀软进程,名称暂未收录",
	"htlog.exe": "已知杀软进程,名称暂未收录",
	"hwpe.exe": "已知杀软进程,名称暂未收录",
	"hxdl.exe": "已知杀软进程,名称暂未收录",
	"hxiul.exe": "已知杀软进程,名称暂未收录",
	"ibmasn.exe": "已知杀软进程,名称暂未收录",
	"ibmavsp.exe": "已知杀软进程,名称暂未收录",
	"icload95.exe": "已知杀软进程,名称暂未收录",
	"icloadnt.exe": "已知杀软进程,名称暂未收录",
	"icmon.exe": "已知杀软进程,名称暂未收录",
	"icsupp95.exe": "已知杀软进程,名称暂未收录",
	"icsuppnt.exe": "已知杀软进程,名称暂未收录",
	"idle.exe": "已知杀软进程,名称暂未收录",
	"iedll.exe": "已知杀软进程,名称暂未收录",
	"ifw2000.exe": "已知杀软进程,名称暂未收录",
	"inetlnfo.exe": "已知杀软进程,名称暂未收录",
	"init.exe": "已知杀软进程,名称暂未收录",
	"intren.exe": "已知杀软进程,名称暂未收录",
	"iomon98.exe": "已知杀软进程,名称暂未收录",
	"istsvc.exe": "已知杀软进程,名称暂未收录",
	"jammer.exe": "已知杀软进程,名称暂未收录",
	"jdbgmrg.exe": "已知杀软进程,名称暂未收录",
	"jedi.exe": "已知杀软进程,名称暂未收录",
	"kavlite40eng.exe": "已知杀软进程,名称暂未收录",
	"kavpers40eng.exe": "已知杀软进程,名称暂未收录",
	"kerio-pf-213-en-win.exe": "已知杀软进程,名称暂未收录",
	"kerio-wrl-421-en-win.exe": "已知杀软进程,名称暂未收录",
	"kerio-wrp-421-en-win.exe": "已知杀软进程,名称暂未收录",
	"kernel32.exe": "已知杀软进程,名称暂未收录",
	"killprocesssetup161.exe": "已知杀软进程,名称暂未收录",
	"ldnetmon.exe": "已知杀软进程,名称暂未收录",
	"ldpro.exe": "已知杀软进程,名称暂未收录",
	"ldpromenu.exe": "已知杀软进程,名称暂未收录",
	"lnetinfo.exe": "已知杀软进程,名称暂未收录",
	"loader.exe": "已知杀软进程,名称暂未收录",
	"localnet.exe": "已知杀软进程,名称暂未收录",
	"lockdown.exe": "已知杀软进程,名称暂未收录",
	"lockdown2000.exe": "已知杀软进程,名称暂未收录",
	"lookout.exe": "已知杀软进程,名称暂未收录",
	"lordpe.exe": "已知杀软进程,名称暂未收录",
	"lsetup.exe": "已知杀软进程,名称暂未收录",
	"luinit.exe": "已知杀软进程,名称暂未收录",
	"luspt.exe": "已知杀软进程,名称暂未收录",
	"mapisvc32.exe": "已知杀软进程,名称暂未收录",
	"md.exe": "已知杀软进程,名称暂未收录",
	"monitor.exe": "已知杀软进程,名称暂未收录",
	"moolive.exe": "已知杀软进程,名称暂未收录",
	"mrflux.exe": "已知杀软进程,名称暂未收录",
	"msapp.exe": "已知杀软进程,名称暂未收录",
	"msbb.exe": "已知杀软进程,名称暂未收录",
	"msblast.exe": "已知杀软进程,名称暂未收录",
	"msccn32.exe": "已知杀软进程,名称暂未收录",
	"msconfig.exe": "已知杀软进程,名称暂未收录",
	"msdm.exe": "已知杀软进程,名称暂未收录",
	"msdos.exe": "已知杀软进程,名称暂未收录",
	"msinfo32.exe": "已知杀软进程,名称暂未收录",
	"mslaugh.exe": "已知杀软进程,名称暂未收录",
	"msmsgri32.exe": "已知杀软进程,名称暂未收录",
	"mssmmc32.exe": "已知杀软进程,名称暂未收录",
	"mssys.exe": "已知杀软进程,名称暂未收录",
	"mu0311ad.exe": "已知杀软进程,名称暂未收录",
	"mwatch.exe": "已知杀软进程,名称暂未收录",
	"n32scanw.exe": "已知杀软进程,名称暂未收录",
	"navap.exe": "已知杀软进程,名称暂未收录",
	"navdx.exe": "已知杀软进程,名称暂未收录",
	"navnt.exe": "已知杀软进程,名称暂未收录",
	"navstub.exe": "已知杀软进程,名称暂未收录",
	"navwnt.exe": "已知杀软进程,名称暂未收录",
	"nc2000.exe": "已知杀软进程,名称暂未收录",
	"ncinst4.exe": "已知杀软进程,名称暂未收录",
	"neomonitor.exe": "已知杀软进程,名称暂未收录",
	"netarmor.exe": "已知杀软进程,名称暂未收录",
	"netd32.exe": "已知杀软进程,名称暂未收录",
	"netinfo.exe": "已知杀软进程,名称暂未收录",
	"netmon.exe": "已知杀软进程,名称暂未收录",
	"netscanpro.exe": "已知杀软进程,名称暂未收录",
	"netspyhunter-1.2.exe": "已知杀软进程,名称暂未收录",
	"netstat.exe": "已知杀软进程,名称暂未收录",
	"netutils.exe": "已知杀软进程,名称暂未收录",
	"normist.exe": "已知杀软进程,名称暂未收录",
	"norton_internet_secu_3.0_407.exe": "已知杀软进程,名称暂未收录",
	"notstart.exe": "已知杀软进程,名称暂未收录",
	"npf40_tw_98_nt_me_2k.exe": "已知杀软进程,名称暂未收录",
	"npfmessenger.exe": "已知杀软进程,名称暂未收录",
	"nsched32.exe": "已知杀软进程,名称暂未收录",
	"nssys32.exe": "已知杀软进程,名称暂未收录",
	"nstask32.exe": "已知杀软进程,名称暂未收录",
	"nsupdate.exe": "已知杀软进程,名称暂未收录",
	"nt.exe": "已知杀软进程,名称暂未收录",
	"ntvdm.exe": "已知杀软进程,名称暂未收录",
	"ntxconfig.exe": "已知杀软进程,名称暂未收录",
	"nui.exe": "已知杀软进程,名称暂未收录",
	"nupgrade.exe": "已知杀软进程,名称暂未收录",
	"nvarch16.exe": "已知杀软进程,名称暂未收录",
	"nvc95.exe": "已知杀软进程,名称暂未收录",
	"nvsvc32.exe": "已知杀软进程,名称暂未收录",
	"nwinst4.exe": "已知杀软进程,名称暂未收录",
	"nwservice.exe": "已知杀软进程,名称暂未收录",
	"nwtool16.exe": "已知杀软进程,名称暂未收录",
	"ollydbg.exe": "已知杀软进程,名称暂未收录",
	"onsrvr.exe": "已知杀软进程,名称暂未收录",
	"optimize.exe": "已知杀软进程,名称暂未收录",
	"ostronet.exe": "已知杀软进程,名称暂未收录",
	"otfix.exe": "已知杀软进程,名称暂未收录",
	"outpostproinstall.exe": "已知杀软进程,名称暂未收录",
	"padmin.exe": "已知杀软进程,名称暂未收录",
	"panixk.exe": "已知杀软进程,名称暂未收录",
	"pavcl.exe": "已知杀软进程,名称暂未收录",
	"pavsched.exe": "已知杀软进程,名称暂未收录",
	"pavw.exe": "已知杀软进程,名称暂未收录",
	"pccwin98.exe": "已知杀软进程,名称暂未收录",
	"pcfwallicon.exe": "已知杀软进程,名称暂未收录",
	"pcip10117_0.exe": "已知杀软进程,名称暂未收录",
	"pdsetup.exe": "已知杀软进程,名称暂未收录",
	"periscope.exe": "已知杀软进程,名称暂未收录",
	"perswf.exe": "已知杀软进程,名称暂未收录",
	"pf2.exe": "已知杀软进程,名称暂未收录",
	"pfwadmin.exe": "已知杀软进程,名称暂未收录",
	"pingscan.exe": "已知杀软进程,名称暂未收录",
	"platin.exe": "已知杀软进程,名称暂未收录",
	"popscan.exe": "已知杀软进程,名称暂未收录",
	"portdetective.exe": "已知杀软进程,名称暂未收录",
	"portmonitor.exe": "已知杀软进程,名称暂未收录",
	"ppinupdt.exe": "已知杀软进程,名称暂未收录",
	"pptbc.exe": "已知杀软进程,名称暂未收录",
	"ppvstop.exe": "已知杀软进程,名称暂未收录",
	"procdump.exe": "已知杀软进程,名称暂未收录",
	"procexplorerv1.0.exe": "已知杀软进程,名称暂未收录",
	"programauditor.exe": "已知杀软进程,名称暂未收录",
	"proport.exe": "已知杀软进程,名称暂未收录",
	"pspf.exe": "已知杀软进程,名称暂未收录",
	"purge.exe": "已知杀软进程,名称暂未收录",
	"rav7.exe": "已知杀软进程,名称暂未收录",
	"rav7win.exe": "已知杀软进程,名称暂未收录",
	"rav8win32eng.exe": "已知杀软进程,名称暂未收录",
	"ray.exe": "已知杀软进程,名称暂未收录",
	"reged.exe": "已知杀软进程,名称暂未收录",
	"regedit.exe": "已知杀软进程,名称暂未收录",
	"regedt32.exe": "已知杀软进程,名称暂未收录",
	"rescue.exe": "已知杀软进程,名称暂未收录",
	"rrguard.exe": "已知杀软进程,名称暂未收录",
	"rshell.exe": "已知杀软进程,名称暂未收录",
	"rundll.exe": "已知杀软进程,名称暂未收录",
	"rundll16.exe": "已知杀软进程,名称暂未收录",
	"ruxdll32.exe": "已知杀软进程,名称暂未收录",
	"sahagent.exe": "已知杀软进程,名称暂未收录",
	"save.exe": "已知杀软进程,名称暂未收录",
	"savenow.exe": "已知杀软进程,名称暂未收录",
	"sc.exe": "已知杀软进程,名称暂未收录",
	"scam32.exe": "已知杀软进程,名称暂未收录",
	"scan95.exe": "已知杀软进程,名称暂未收录",
	"scanpm.exe": "已知杀软进程,名称暂未收录",
	"serv95.exe": "已知杀软进程,名称暂未收录",
	"setup_flowprotector_us.exe": "已知杀软进程,名称暂未收录",
	"setupvameeval.exe": "已知杀软进程,名称暂未收录",
	"sgssfw32.exe": "已知杀软进程,名称暂未收录",
	"shellspyinstall.exe": "已知杀软进程,名称暂未收录",
	"shn.exe": "已知杀软进程,名称暂未收录",
	"sms.exe": "已知杀软进程,名称暂未收录",
	"smss32.exe": "已知杀软进程,名称暂未收录",
	"sofi.exe": "已知杀软进程,名称暂未收录",
	"sperm.exe": "已知杀软进程,名称暂未收录",
	"spf.exe": "已知杀软进程,名称暂未收录",
	"spoler.exe": "已知杀软进程,名称暂未收录",
	"spoolcv.exe": "已知杀软进程,名称暂未收录",
	"spoolsv32.exe": "已知杀软进程,名称暂未收录",
	"spyxx.exe": "已知杀软进程,名称暂未收录",
	"srng.exe": "已知杀软进程,名称暂未收录",
	"ss3edit.exe": "已知杀软进程,名称暂未收录",
	"ssg_4104.exe": "已知杀软进程,名称暂未收录",
	"ssgrate.exe": "已知杀软进程,名称暂未收录",
	"st2.exe": "已知杀软进程,名称暂未收录",
	"start.exe": "已知杀软进程,名称暂未收录",
	"stcloader.exe": "已知杀软进程,名称暂未收录",
	"supftrl.exe": "已知杀软进程,名称暂未收录",
	"support.exe": "已知杀软进程,名称暂未收录",
	"svchosts.exe": "已知杀软进程,名称暂未收录",
	"sweep95.exe": "已知杀软进程,名称暂未收录",
	"sweepnet.sweepsrv.sys.swnetsup.exe": "已知杀软进程,名称暂未收录",
	"sysedit.exe": "已知杀软进程,名称暂未收录",
	"sysupd.exe": "已知杀软进程,名称暂未收录",
	"taskmg.exe": "已知杀软进程,名称暂未收录",
	"taskmo.exe": "已知杀软进程,名称暂未收录",
	"taumon.exe": "已知杀软进程,名称暂未收录",
	"tc.exe": "已知杀软进程,名称暂未收录",
	"tca.exe": "已知杀软进程,名称暂未收录",
	"tcm.exe": "已知杀软进程,名称暂未收录",
	"tds-3.exe": "已知杀软进程,名称暂未收录",
	"tds2-98.exe": "已知杀软进程,名称暂未收录",
	"tds2-nt.exe": "已知杀软进程,名称暂未收录",
	"teekids.exe": "已知杀软进程,名称暂未收录",
	"tfak.exe": "已知杀软进程,名称暂未收录",
	"tfak5.exe": "已知杀软进程,名称暂未收录",
	"tgbob.exe": "已知杀软进程,名称暂未收录",
	"titaninxp.exe": "已知杀软进程,名称暂未收录",
	"tracert.exe": "已知杀软进程,名称暂未收录",
	"trickler.exe": "已知杀软进程,名称暂未收录",
	"trjscan.exe": "已知杀软进程,名称暂未收录",
	"trjsetup.exe": "已知杀软进程,名称暂未收录",
	"trojantrap3.exe": "已知杀软进程,名称暂未收录",
	"tsadbot.exe": "已知杀软进程,名称暂未收录",
	"undoboot.exe": "已知杀软进程,名称暂未收录",
	"updat.exe": "已知杀软进程,名称暂未收录",
	"update.exe": "已知杀软进程,名称暂未收录",
	"upgrad.exe": "已知杀软进程,名称暂未收录",
	"utpost.exe": "已知杀软进程,名称暂未收录",
	"vbcmserv.exe": "已知杀软进程,名称暂未收录",
	"vbcons.exe": "已知杀软进程,名称暂未收录",
	"vbust.exe": "已知杀软进程,名称暂未收录",
	"vbwin9x.exe": "已知杀软进程,名称暂未收录",
	"vbwinntw.exe": "已知杀软进程,名称暂未收录",
	"vcsetup.exe": "已知杀软进程,名称暂未收录",
	"vet32.exe": "已知杀软进程,名称暂未收录",
	"vet95.exe": "已知杀软进程,名称暂未收录",
	"vfsetup.exe": "已知杀软进程,名称暂未收录",
	"vir-help.exe": "已知杀软进程,名称暂未收录",
	"virusmdpersonalfirewall.exe": "已知杀软进程,名称暂未收录",
	"vnlan300.exe": "已知杀软进程,名称暂未收录",
	"vnpc3000.exe": "已知杀软进程,名称暂未收录",
	"vpfw30s.exe": "已知杀软进程,名称暂未收录",
	"vscan40.exe": "已知杀软进程,名称暂未收录",
	"vscenu6.02d30.exe": "已知杀软进程,名称暂未收录",
	"vsched.exe": "已知杀软进程,名称暂未收录",
	"vsecomr.exe": "已知杀软进程,名称暂未收录",
	"vsisetup.exe": "已知杀软进程,名称暂未收录",
	"vswin9xe.exe": "已知杀软进程,名称暂未收录",
	"vswinntse.exe": "已知杀软进程,名称暂未收录",
	"vswinperse.exe": "已知杀软进程,名称暂未收录",
	"w32dsm89.exe": "已知杀软进程,名称暂未收录",
	"w9x.exe": "已知杀软进程,名称暂未收录",
	"watchdog.exe": "已知杀软进程,名称暂未收录",
	"webdav.exe": "已知杀软进程,名称暂未收录",
	"webtrap.exe": "已知杀软进程,名称暂未收录",
	"wfindv32.exe": "已知杀软进程,名称暂未收录",
	"whoswatchingme.exe": "已知杀软进程,名称暂未收录",
	"wimmun32.exe": "已知杀软进程,名称暂未收录",
	"win-bugsfix.exe": "已知杀软进程,名称暂未收录",
	"win32.exe": "已知杀软进程,名称暂未收录",
	"win32us.exe": "已知杀软进程,名称暂未收录",
	"winactive.exe": "已知杀软进程,名称暂未收录",
	"window.exe": "已知杀软进程,名称暂未收录",
	"windows.exe": "已知杀软进程,名称暂未收录",
	"wininetd.exe": "已知杀软进程,名称暂未收录",
	"wininitx.exe": "已知杀软进程,名称暂未收录",
	"winlogin.exe": "已知杀软进程,名称暂未收录",
	"winmain.exe": "已知杀软进程,名称暂未收录",
	"winnet.exe": "已知杀软进程,名称暂未收录",
	"winppr32.exe": "已知杀软进程,名称暂未收录",
	"winrecon.exe": "已知杀软进程,名称暂未收录",
	"winservn.exe": "已知杀软进程,名称暂未收录",
	"winssk32.exe": "已知杀软进程,名称暂未收录",
	"winstart.exe": "已知杀软进程,名称暂未收录",
	"winstart001.exe": "已知杀软进程,名称暂未收录",
	"wintsk32.exe": "已知杀软进程,名称暂未收录",
	"winupdate.exe": "已知杀软进程,名称暂未收录",
	"wkufind.exe": "已知杀软进程,名称暂未收录",
	"wnad.exe": "已知杀软进程,名称暂未收录",
	"wnt.exe": "已知杀软进程,名称暂未收录",
	"wradmin.exe": "已知杀软进程,名称暂未收录",
	"wrctrl.exe": "已知杀软进程,名称暂未收录",
	"wsbgate.exe": "已知杀软进程,名称暂未收录",
	"wupdater.exe": "已知杀软进程,名称暂未收录",
	"wupdt.exe": "已知杀软进程,名称暂未收录",
	"wyvernworksfirewall.exe": "已知杀软进程,名称暂未收录",
	"xpf202en.exe": "已知杀软进程,名称暂未收录",
	"zapsetup3001.exe": "已知杀软进程,名称暂未收录",
	"zatutor.exe": "已知杀软进程,名称暂未收录",
	"zonalm2601.exe": "已知杀软进程,名称暂未收录",
	"akrnl.exe": "已知杀软进程,名称暂未收录",
	"trojan.exe": "已知杀软进程,名称暂未收录",
	"antivir.exe": "已知杀软进程,名称暂未收录",
	"armor2net.exe": "已知杀软进程,名称暂未收录",
	"ashenhcd.exe": "已知杀软进程,名称暂未收录",
	"ashpopwz.exe": "已知杀软进程,名称暂未收录",
	"ashskpck.exe": "已知杀软进程,名称暂未收录",
	"aveval.exe": "已知杀软进程,名称暂未收录",
	"avevl32.exe": "已知杀软进程,名称暂未收录",
	"avgam.exe": "已知杀软进程,名称暂未收录",
	"avgcc.exe": "已知杀软进程,名称暂未收录",
	"avxmonitor.exe": "已知杀软进程,名称暂未收录",
	"cafix.exe": "已知杀软进程,名称暂未收录",
	"bitdefender.exe": "已知杀软进程,名称暂未收录",
	"cfpconfig.exe": "已知杀软进程,名称暂未收录",
	"drvirus.exe": "已知杀软进程,名称暂未收录",
	"dwebllio.exe": "已知杀软进程,名称暂未收录",
	"dwebio.exe": "已知杀软进程,名称暂未收录",
	"escanh95.exe": "已知杀软进程,名称暂未收录",
	"filemon.exe": "已知杀软进程,名称暂未收录",
	"forticlient.exe": "已知杀软进程,名称暂未收录",
	"fortiscan.exe": "已知杀软进程,名称暂未收录",
	"fpavserver.exe": "已知杀软进程,名称暂未收录",
	"f-sched.exe": "已知杀软进程,名称暂未收录",
	"fspex.exe": "已知杀软进程,名称暂未收录",
	"gcasdtserv.exe": "已知杀软进程,名称暂未收录",
	"gcasserv.exe": "已知杀软进程,名称暂未收录",
	"giantantispyware.exe": "已知杀软进程,名称暂未收录",
	"guardxservice.exe": "已知杀软进程,名称暂未收录",
	"guardxkickoff.exe": "已知杀软进程,名称暂未收录",
	"hregmon.exe": "已知杀软进程,名称暂未收录",
	"hrres.exe": "已知杀软进程,名称暂未收录",
	"hsockpe.exe": "已知杀软进程,名称暂未收录",
	"hupdate.exe": "已知杀软进程,名称暂未收录",
	"icssuppnt.exe": "已知杀软进程,名称暂未收录",
	"inetupd.exe": "已知杀软进程,名称暂未收录",
	"isatray.exe": "已知杀软进程,名称暂未收录",
	"mamutu.exe": "已知杀软进程,名称暂未收录",
	"npavtray.exe": "已知杀软进程,名称暂未收录",
	"nssserv.exe": "已知杀软进程,名称暂未收录",
	"nsstray.exe": "已知杀软进程,名称暂未收录",
	"ntos.exe": "已知杀软进程,名称暂未收录",
	"nvcod.exe": "已知杀软进程,名称暂未收录",
	"nvcte.exe": "已知杀软进程,名称暂未收录",
	"nvcut.exe": "已知杀软进程,名称暂未收录",
	"onlinent.exe": "已知杀软进程,名称暂未收录",
	"opssvc.exe": "已知杀软进程,名称暂未收录",
	"pcctlcom.exe": "已知杀软进程,名称暂未收录",
	"pertsk.exe": "已知杀软进程,名称暂未收录",
	"pervac.exe": "已知杀软进程,名称暂未收录",
	"pnmsrv.exe": "已知杀软进程,名称暂未收录",
	"prevx.exe": "已知杀软进程,名称暂未收录",
	"psimsvc.exe": "已知杀软进程,名称暂未收录",
	"qhonline.exe": "已知杀软进程,名称暂未收录",
	"qhonsvc.exe": "已知杀软进程,名称暂未收录",
	"qhwscsvc.exe": "已知杀软进程,名称暂未收录",
	"qhset.exe": "已知杀软进程,名称暂未收录",
	"sality.exe": "已知杀软进程,名称暂未收录",
	"sapissvc.exe": "已知杀软进程,名称暂未收录",
	"scanwscs.exe": "已知杀软进程,名称暂未收录",
	"scanningprocess.exe": "已知杀软进程,名称暂未收录",
	"sdra64.exe": "已知杀软进程,名称暂未收录",
	"sitecli.exe": "已知杀软进程,名称暂未收录",
	"stopsignav.exe": "已知杀软进程,名称暂未收录",
	"vba32ecm.exe": "已知杀软进程,名称暂未收录",
	"vba32ifs.exe": "已知杀软进程,名称暂未收录",
	"vba32ldr.exe": "已知杀软进程,名称暂未收录",
	"vba32pp3.exe": "已知杀软进程,名称暂未收录",
	"vbsntw.exe": "已知杀软进程,名称暂未收录",
	"vrfwsvc.exe": "已知杀软进程,名称暂未收录",
	"vrrw32.exe": "已知杀软进程,名称暂未收录",
	"winssnotify.exe": "已知杀软进程,名称暂未收录",
	"zlclient.exe": "已知杀软进程,名称暂未收录",
};