avList = {
    "d_safe_manage.exe": "d盾", 
    "d_manage.exe": "d盾", 
    "pc.exe": "云锁客户端", 
    "yunsuo_agent_service.exe": "云锁服务端", 
    "yunsuo_agent_daemon.exe": "云锁服务端", 
    "gov_defence_daemon.exe": "govdefence(网防g01)", 
    "gov_defence_service.exe": "govdefence(网防g01)", 
    "aliyundun.exe": "阿里云-云盾", 
    "alisecguard.exe": "阿里云-云盾", 
    "aliyundunupdate.exe": "阿里云-升级服务", 
    "aliyun_assist_service.exe": "阿里云-云监控", 
    "baradagent.exe": "腾讯云-安全监控组件", 
    "sgagent.exe": "腾讯云-安全监控组件", 
    "ydservice.exe": "腾讯云-云镜主机安全",
    "ydlive.exe": "腾讯云-云镜主机安全", 
    "ydedr.exe": "腾讯云-云镜主机安全",
    "360websafe.exe": "360主机卫士", 
    "qhsrv.exe": "360主机卫士", 
    "qhwebshellguard.exe": "360主机卫士", 
    "cloudhelper.exe": "安全狗", 
    "safedogtray.exe": "安全狗", 
    "safedogguardcenter.exe": "安全狗", 
    "safedogupdatecenter.exe": "安全狗", 
    "safedogsiteapache.exe": "网站安全狗(apache)", 
    "safedogsiteiis.exe": "网站安全狗(iis)", 
    "safedogserverui.exe": "服务器安全狗", 
    "hws.exe": "护卫神·入侵防护系统", 
    "hwsd.exe": "护卫神·入侵防护系统", 
    "hws_ui.exe": "护卫神·入侵防护系统", 
    "hwspanel.exe": "护卫神·入侵防护系统", 
    "hipsdaemon.exe": "火绒安全软件",  	
    "hipstray.exe": "火绒安全软件", 
    "hipslog.exe": "火绒安全软件", 
    "hipsmain.exe": "火绒安全软件", 
    "usysdiag.exe": "火绒安全软件", 
    "wsctrl.exe": "火绒安全软件", 
    "qqpcrtp.exe": "腾讯电脑管家", 
    "qqpctray.exe": "腾讯电脑管家", 
    "qqpcnetflow.exe": "腾讯电脑管家", 
    "qqpcrealtimespeedup.exe": "腾讯电脑管家", 
    "360sd.exe": "360杀毒", 
    "360rp.exe": "360杀毒", 
    "360safe.exe": "360安全卫士", 
    "360tray.exe": "360实时保护", 
    "liveupdate360.exe": "360更新程序", 
    "zhudongfangyu.exe": "360主动防御", 
    "360safebox.exe": "360保险箱主程序", 
    "360skylarsvc.exe": "360天擎终端安全管理系统", 
    "wdswfsafe.exe": "360杀毒-网盾", 
    "QHActiveDefense.exe": "360国际版", 
    "360EntMisc.exe": "360(奇安信)天擎", 
    "360EntClient.exe": "天擎EDR Agent", 
    "edr_sec_plan.exe": "深信服EDR Agent", 
    "edr_monitor.exe": "深信服EDR Agent", 
    "edr_agent.exe": "深信服EDR Agent", 
    "ESCCControl.exe": "启明星辰天珣EDR Agent", 
    "ESCC.exe": "启明星辰天珣EDR Agent", 
    "ESAV.exe": "启明星辰天珣EDR Agent", 
    "ESCCIndex.exe": "启明星辰天珣EDR Agent", 
    "savmain.exe": "Sophos杀毒", 
    "savprogress.exe": "Sophos杀毒", 
    "Sophos UI.exe": "Sophos杀毒", 
    "SophosCleanM.exe": "Sophos杀毒", 
    "SophosFileScanner.exe": "Sophos杀毒", 
    "SophosOsquery.exe": "Sophos杀毒", 
    "SophosNtpService.exe": "Sophos杀毒", 
    "SophosFS.exe": "Sophos File Scanner Service", 
    "SophosHealth.exe": "Sophos Health Service", 
    "SophosSafestore64.exe": "Sophos Safestore Service", 
    "SEDService.exe": "Sophos Endpoint Defense Service", 
    "ALsvc.exe": "Sophos AutoUpdate Service", 
    "SophosCleanM64.exe": "Sophos Clean Service", 
    "McsAgent.exe": "Sophos MCS Agent", 
    "McsClient.exe": "Sophos MCS Client", 
    "SSPService.exe": "Sophos System Protection Service", 
    "swc_service.exe": "Sophos Web Control Service", 
    "SophosFIMService.exe": "Sophos FIM", 
    "sdcservice.exe": "Sophos Device Control Service", 
    "mbam.exe": "malwarebytes杀毒", 
    "mbamtray.exe": "malwarebytes杀毒", 
    "mbamservice.exe": "malwarebytes杀毒", 
    "tmbmsrv.exe": "pc-cillin趋势反病毒", 
    "ntrtscan.exe": "pc-cillin趋势反病毒", 
    "vstskmgr.exe": "mcafee(麦咖啡)", 
    "mcshield.exe": "mcafee(麦咖啡)", 
    "mfevtps.exe": "mcafee(麦咖啡)", 
    "mfeann.exe": "mcafee(麦咖啡)", 
    "tbmon.exe": "mcafee(麦咖啡)", 
    "shstat.exe": "mcafee(麦咖啡)", 
    "mctray.exe": "mcafee(麦咖啡)", 
    "udaterui.exe": "mcafee(麦咖啡)", 
    "naprdmgr.exe": "mcafee(麦咖啡)", 
    "engineserver.exe": "mcafee(麦咖啡)", 
    "frameworkservice.exe": "mcafee(麦咖啡)", 
    "avk.exe": "gdata安全防护软件", 
    "gdscan.exe": "gdata安全防护软件", 
    "avkwctl.exe": "gdata安全防护软件", 
    "avkcl.exe": "gdata安全防护软件", 
    "avkproxy.exe": "gdata安全防护软件", 
    "avkbackupservice.exe": "gdata安全防护软件", 
    "ccevtmgr.exe": "symantec(赛门铁克)", 
    "ccsetmgr.exe": "symantec(赛门铁克)", 
    "ccsvchst.exe": "symantec(赛门铁克) 或 norton(诺顿杀毒)", 
    "rtvscan.exe": "symantec(赛门铁克) 或 norton(诺顿杀毒)", 
    "smc.exe": "symantec(赛门铁克)", 
    "smcgui.exe": "symantec(赛门铁克)", 
    "snac.exe": "symantec(赛门铁克)", 
    "symcorpui.exe": "symantec(赛门铁克)", 
    "msmpeng.exe": "windows defender", 
    "nissrv.exe": "windows defender", 
    "mssense.exe": "windows defender", 
    "msseces.exe": "windows defender", 
    "mpcmdrun.exe": "windows defender", 
    "msascui.exe": "windows defender", 
    "msascuil.exe": "windows defender", 
    "securityhealthservice.exe": "windows defender", 
    "smartscreen.exe": "windows defender smartscreen", 
    "avp.exe": "kaspersky(卡巴斯基)", 
    "kavfs.exe": "kaspersky(卡巴斯基)", 
    "klnagent.exe": "kaspersky(卡巴斯基)", 
    "kavtray.exe": "kaspersky(卡巴斯基)", 
    "kavfswp.exe": "kaspersky(卡巴斯基)", 
    "ekrn.exe": "eset nod32防毒", 
    "egui.exe": "eset nod32防毒", 
    "eshasrv.exe": "eset nod32防毒", 
    "eguiproxy.exe": "eset nod32防毒", 
    "avg.exe": "avg杀毒", 
    "avgwdsvc.exe": "avg杀毒", 
    "avastui.exe": "avast!5主程序", 
    "ashdisp.exe": "avast网络安全", 
    "clamtray.exe": "clemwin free antivirus", 
    "clamscan.exe": "clemwin free antivirus", 
    "avcenter.exe": "avira(小红伞)", 
    "avguard.exe": "avira(小红伞)", 
    "avgnt.exe": "avira(小红伞)", 
    "sched.exe": "avira(小红伞)", 
    "bddownloader.exe": "百度卫士", 
    "baidusafetray.exe": "百度卫士", 
    "baiduansvx.exe": "百度卫士-主进程", 
    "baidusd.exe": "百度杀毒-主程序", 
    "baidusdsvc.exe": "百度杀毒-服务进程", 
    "baidusdtray.exe": "百度杀毒-托盘进程", 
    "f-prot.exe": "f-prot杀毒", 
    "vba32lder.exe": "vb32杀毒", 
    "k7tsecurity.exe": "k7杀毒", 
    "iptray.exe": "immunet杀毒", 
    "cmctrayicon.exe": "cmc杀毒", 
    "bkavservice.exe": "bkav杀毒", 
    "nspupsvc.exe": "nprotect杀毒", 
    "a2guard.exe": "a-squared杀毒", 
    "ad-watch.exe": "lavasoft杀毒", 
    "unthreat.exe": "unthreat杀毒", 
    "psafesystray.exe": "psafe反病毒", 
    "patray.exe": "ahnlab安博士杀毒", 
    "v3svc.exe": "ahnlab安博士v3杀毒", 
    "cleaner8.exe": "the cleaner杀毒", 
    "mongoosagui.exe": "mongoosa杀毒", 
    "secenter.exe": "bitdefender杀毒", 
    "ayagent.exe": "alyac韩国胶囊杀毒", 
    "ksafe.exe": "金山卫士", 
    "kvmonxp.exe": "江民杀毒", 
    "ravmon.exe": "瑞星杀毒", 
    "ravmond.exe": "瑞星杀毒", 
    "kxescore.exe": "金山毒霸", 
    "kupdata.exe": "金山毒霸", 
    "kxetray.exe": "金山毒霸", 
    "kwsprotect64.exe": "金山毒霸", 
    "ksafetray.exe": "金山卫士", 
    "knsdtray.exe": "可牛杀毒", 
    "sbamsvc.exe": "vipre杀毒", 
    "remupd.exe": "熊猫卫士杀毒", 
    "spidernt.exe": "dr.web杀毒", 
    "quhlpsvc.exe": "quickheal杀毒", 
    "fsavgui.exe": "f-secure冰岛杀毒", 
    "f-secure.exe": "f-secure冰岛杀毒", 
    "arcatasksservice.exe": "arcavir杀毒", 
    "vsserv.exe": "bitdefender比特梵德杀毒", 
    "avwatchservice.exe": "virusfighter杀毒", 
    "ns.exe": "norton诺顿杀毒", 
    "ccapp.exe": "norton诺顿杀毒", 
    "vptray.exe": "norton病毒防火墙-盾牌图标程序", 
    "npfmntor.exe": "norton杀毒软件相关进程", 
    "ccregvfy.exe": "norton杀毒软件自身完整性检查程序", 
    "sndsrvc.exe": "symantec shared诺顿邮件防火墙软件", 
    "spbbcsvc.exe": "symantec shared诺顿邮件防火墙软件", 
    "symlcsvc.exe": "symantec shared诺顿邮件防火墙软件", 
    "coranticontrolcenter32.exe": "coranti2012杀毒", 
    "cksoftshiedantivirus4.exe": "shield antivirus杀毒", 
    "spywareterminatorshield.exe": "spywareterminator杀毒", 
    "usbkiller.exe": "u盘杀毒专家", 
    "ast.exe": "超级巡警", 
    "fortitray.exe": "飞塔", 
    "gg.exe": "巨盾网游安全盾", 
    "adam.exe": "绿鹰安全精灵", 
    "kpfwtray.exe": "金山网镖", 
    "beikesan.exe": "贝壳云安全", 
    "parmor.exe": "木马克星", 
    "iparmor.exe": "木马克星", 
    "kswebshield.exe": "金山网盾", 
    "trojanhunter.exe": "木马猎手", 
    "webscanx.exe": "网络病毒克星", 
    "ananwidget.exe": "墨者安全专家", 
    "pfw.exe": "天网防火墙", 
    "cfp.exe": "comodo科摩多", 
    "mpmon.exe": "微点主动防御", 
    "rfwmain.exe": "瑞星防火墙", 
    "sphinx.exe": "sphinx防火墙", 
    "vsmon.exe": "zonealarm防火墙", 
    "fyfirewall.exe": "风云防火墙", 
    "acs.exe": "outpost防火墙", 
    "outpost.exe": "outpost防火墙"
};